[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"


[project]
name = "PostMD"
version = "0.0.2"
authors = [
  { name="sszhang", email="zhangshusong789@gmail.com" },
]
description = "A simple package for post-processing of data from LAMMPS"
readme = "README.md"
requires-python = ">=3.7"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]

