name: Sphinx build

on:
    push:
      branches:    
        - dev

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    # Standard drop-in approach that should work for most people.
    # - name: Build HTML
    #   uses: ammaraskar/sphinx-action@master
    #   with:
    #     docs-folder: "docs/"
    - uses: actions/setup-python@v3
    - name: Install dependencies
      run: |
        pip install sphinx sphinx_rtd_theme
    - name: Sphinx build
      run: |
        pwd
        ls -l
        cd docs
        ls -l
        make help
    # Great extra actions to compose with:
    # Create an artifact of the html output.
    - name: Upload artifacts
      uses: actions/upload-artifact@v1
      with:
        name: html-docs
        path: docs/_build/html/

    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      if: github.ref == 'refs/heads/dev'
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: docs/build/html